version: '3.8'

services:
  web:
    build: .
    container_name: innerarchitect_web
    restart: always
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/inner_architect
      - SECRET_KEY=dev_secret_key_inner_architect
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - app_network
    command: python app.py

  db:
    image: postgres:13
    container_name: innerarchitect_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inner_architect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network



networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: